from django.urls import path
from .admin_portal_views import (
    admin_dashboard,
    admin_tenants,
    admin_tenant_detail,
    admin_billing,
    admin_payments,
    admin_maintenance,
    admin_announcements,
    admin_create_tenant_profile,
    admin_create_announcement,
    admin_create_lease,
    admin_create_unit,
    admin_edit_tenant,
    admin_delete_tenant,
    admin_edit_lease,
    admin_delete_lease,
    admin_edit_announcement,
    admin_delete_announcement,
    admin_mark_bill_paid,
    admin_mark_bill_unpaid,
    admin_approve_payment,
    admin_reject_payment,
    admin_update_maintenance,
)

urlpatterns = [
    path("dashboard/", admin_dashboard, name="admin_dashboard"),
    path("tenants/", admin_tenants, name="admin_tenants"),
    path("tenants/<int:tenant_id>/", admin_tenant_detail, name="admin_tenant_detail"),
    path("tenants/<int:tenant_id>/edit/", admin_edit_tenant, name="admin_edit_tenant"),
    path("tenants/<int:tenant_id>/delete/", admin_delete_tenant, name="admin_delete_tenant"),
    path("billing/", admin_billing, name="admin_billing"),
    path("billing/mark_paid/<int:bill_id>/", admin_mark_bill_paid, name="admin_mark_bill_paid"),
    path("billing/mark_unpaid/<int:bill_id>/", admin_mark_bill_unpaid, name="admin_mark_bill_unpaid"),
    path("payments/", admin_payments, name="admin_payments"),
    path("payments/<int:payment_id>/approve/", admin_approve_payment, name="admin_approve_payment"),
    path("payments/<int:payment_id>/reject/", admin_reject_payment, name="admin_reject_payment"),
    path("maintenance/", admin_maintenance, name="admin_maintenance"),
    path("maintenance/<int:req_id>/update/", admin_update_maintenance, name="admin_update_maintenance"),
    path("announcements/", admin_announcements, name="admin_announcements"),

    # Create pages
    path("tenants/add/", admin_create_tenant_profile, name="admin_create_tenant_profile"),
    path("leases/add/", admin_create_lease, name="admin_create_lease"),
    path("units/add/", admin_create_unit, name="admin_create_unit"),
    path("leases/<int:lease_id>/edit/", admin_edit_lease, name="admin_edit_lease"),
    path("leases/<int:lease_id>/delete/", admin_delete_lease, name="admin_delete_lease"),
    path("announcements/add/", admin_create_announcement, name="admin_create_announcement"),
    path("announcements/<int:ann_id>/edit/", admin_edit_announcement, name="admin_edit_announcement"),
    path("announcements/<int:ann_id>/delete/", admin_delete_announcement, name="admin_delete_announcement"),
   
]