# Generated by Django 6.0.2 on 2026-02-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualpayment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='manualpayment',
            name='screenshot',
        ),
        migrations.AddField(
            model_name='manualpayment',
            name='expected_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
