# Generated by Django 6.0.2 on 2026-02-21 13:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_manualpayment_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='manualpayment',
            index=models.Index(fields=['created_at'], name='payments_ma_created_8ace2c_idx'),
        ),
    ]
