# Generated by Django 6.0.2 on 2026-02-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_manualpayment_payments_ma_created_8ace2c_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='manualpayment',
            name='payments_ma_status_cb5faa_idx',
        ),
        migrations.RemoveIndex(
            model_name='manualpayment',
            name='payments_ma_referen_1adc2f_idx',
        ),
        migrations.RemoveIndex(
            model_name='manualpayment',
            name='payments_ma_created_8ace2c_idx',
        ),
        migrations.AlterField(
            model_name='manualpayment',
            name='bill_ids',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.RemoveField(
            model_name='manualpayment',
            name='expected_amount',
        ),
    ]
