# Generated by Django 6.0.2 on 2026-05-07 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_manualpayment_payments_ma_status_cb5faa_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualpayment',
            name='payment_type',
            field=models.CharField(choices=[('full', 'Full Payment'), ('rent_only', 'Rent Only'), ('water_only', 'Water Only')], default='full', max_length=20),
        ),
    ]
