# Generated by Django 6.0.2 on 2026-05-07 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_add_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
