# Generated by Django 6.0.2 on 2026-05-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_manualpayment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualpayment',
            name='payment_method',
            field=models.CharField(choices=[('GCASH', 'GCash QR'), ('CASH', 'Face-to-Face Cash')], default='GCASH', max_length=10),
        ),
        migrations.AddField(
            model_name='manualpayment',
            name='preferred_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manualpayment',
            name='preferred_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manualpayment',
            name='tenant_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='manualpayment',
            name='reference_code',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
