# Generated by Django 6.0.2 on 2026-05-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_manualpayment_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualpayment',
            name='schedule_confirmed',
            field=models.BooleanField(default=False, help_text='Admin has confirmed the F2F appointment time'),
        ),
    ]
