# Generated by Django 6.0.2 on 2026-05-11 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_manualpayment_schedule_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualpayment',
            name='payment_type',
            field=models.CharField(choices=[('full', 'Full Payment'), ('rent_only', 'Rent Only'), ('water_only', 'Water Only'), ('move_in', 'Move-in Payment')], default='full', max_length=20),
        ),
    ]
