# Generated by Django 6.0.2 on 2026-05-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_alter_manualpayment_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualpayment',
            name='checkout_session_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='manualpayment',
            name='checkout_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='manualpayment',
            name='paid_via',
            field=models.CharField(blank=True, default='', help_text='Actual method used in PayMongo (gcash, card, grab_pay, etc.)', max_length=30),
        ),
        migrations.AddField(
            model_name='manualpayment',
            name='paymongo_payment_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='manualpayment',
            name='payment_method',
            field=models.CharField(choices=[('GCASH', 'GCash QR'), ('CASH', 'Face-to-Face Cash'), ('PAYMONGO', 'PayMongo Checkout')], default='GCASH', max_length=10),
        ),
    ]
