# Generated by Django 6.0.2 on 2026-05-25 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_manualpayment_checkout_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualpayment',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Store PayMongo metadata including lease_id, payment_type, etc.'),
        ),
    ]
