# Generated by Django 6.0.2 on 2026-07-06 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_alter_manualpayment_payment_type_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualpayment',
            name='payment_type',
            field=models.CharField(choices=[('full', 'Full Payment'), ('rent_only', 'Monthly Rent'), ('water_only', 'Water Only'), ('maintenance_only', 'Maintenance Charge Only'), ('move_in', 'Move-in Payment')], default='full', max_length=20),
        ),
    ]
