# Generated by Django 6.0.2 on 2026-02-19 19:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_paymenttransaction_months_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='water_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
