# Generated by Django 6.0.2 on 2026-02-19 20:08

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_payment_water_amount'),
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_month', models.DateField()),
                ('due_date', models.DateField()),
                ('base_rent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('water_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('interest', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid')], default='UNPAID', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_bills', to='rentals.lease')),
            ],
            options={
                'ordering': ['-billing_month'],
                'unique_together': {('lease', 'billing_month')},
            },
        ),
    ]
