# Generated by Django 6.0.2 on 2026-02-19 21:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_monthlybill'),
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlybill',
            options={'ordering': ('-billing_month',)},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('-billing_month',)},
        ),
        migrations.AlterModelOptions(
            name='paymenttransaction',
            options={'ordering': ('-paid_at',)},
        ),
        migrations.RemoveConstraint(
            model_name='payment',
            name='unique_payment_per_month',
        ),
        migrations.RemoveField(
            model_name='monthlybill',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='monthlybill',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlybill',
            name='payment_reference',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='lease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='rentals.lease'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_reference',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='lease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='rentals.lease'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='months_paid',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='paid_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='reference',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.RemoveField(
            model_name='payment',
            name='water_amount',
        ),
    ]
