# Generated by Django 6.0.2 on 2026-02-25 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_monthlybill_options_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='lease',
        ),
        migrations.AlterUniqueTogether(
            name='monthlybill',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='PaymentTransaction',
        ),
    ]
