# Generated by Django 6.0.2 on 2026-05-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_remove_paymenttransaction_lease_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybill',
            name='bill_type',
            field=models.CharField(choices=[('RENT', 'Rent'), ('WATER', 'Water'), ('PENALTY', 'Penalty')], default='RENT', max_length=20),
        ),
    ]
