# Generated by Django 6.0.2 on 2026-05-06 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_monthlybill_bill_type'),
        ('rentals', '0017_tenantprofile_password_change_required_and_more'),
        ('water', '0002_alter_waterbill_unit_waterrate_waterreading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybill',
            name='source_water_reading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_monthly_bills', to='water.waterreading'),
        ),
        migrations.AddField(
            model_name='monthlybill',
            name='water_computed_from_system',
            field=models.BooleanField(default=False, help_text='True if water_amount was computed from WaterReading system'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlybill',
            unique_together={('lease', 'billing_month')},
        ),
    ]
