# Generated by Django 6.0.2 on 2026-05-07 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_monthlybill_source_water_reading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybill',
            name='rent_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='monthlybill',
            name='rent_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlybill',
            name='water_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='monthlybill',
            name='water_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
