# Generated by Django 6.0.2 on 2026-05-07 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_add_partial_payment_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlybill',
            name='status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid')], default='UNPAID', max_length=20),
        ),
    ]
