# Generated by Django 6.0.2 on 2026-05-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_alter_monthlybill_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybill',
            name='parking_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monthly parking fee (0 if no parking)', max_digits=10),
        ),
        migrations.AddField(
            model_name='monthlybill',
            name='parking_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
