# Generated by Django 6.0.2 on 2026-06-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_monthlybill_query_indexes'),
        ('rentals', '0029_alter_room_image_alter_unitimage_image'),
        ('water', '0002_alter_waterbill_unit_waterrate_waterreading_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'CREATE INDEX IF NOT EXISTS "bill_month_idx" '
                        'ON "billing_monthlybill" ("billing_month")'
                    ),
                    reverse_sql='DROP INDEX IF EXISTS "bill_month_idx"',
                ),
                migrations.RunSQL(
                    sql=(
                        'CREATE INDEX IF NOT EXISTS "bill_stat_month_idx" '
                        'ON "billing_monthlybill" ("status", "billing_month")'
                    ),
                    reverse_sql='DROP INDEX IF EXISTS "bill_stat_month_idx"',
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name='monthlybill',
                    index=models.Index(fields=['billing_month'], name='bill_month_idx'),
                ),
                migrations.AddIndex(
                    model_name='monthlybill',
                    index=models.Index(fields=['status', 'billing_month'], name='bill_stat_month_idx'),
                ),
            ],
        ),
    ]
