# Generated by Django 6.0.2 on 2026-07-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_billlineitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billlineitem',
            name='line_type',
            field=models.CharField(choices=[('RENT', 'Rent'), ('PARKING', 'Parking'), ('WATER', 'Water'), ('LATE_FEE', 'Late Fee'), ('SECURITY_DEPOSIT', 'Security Deposit'), ('CONTRACT_DEPOSIT', 'Contract Deposit'), ('MAINTENANCE', 'Maintenance')], max_length=30),
        ),
    ]
