# Generated by Django 6.0.2 on 2026-04-17 12:17

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        # Add new fields with defaults first
        migrations.AddField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(
                choices=[('STUDIO', 'Studio'), ('1BR', '1 Bedroom'), ('2BR', '2 Bedrooms'), ('3BR', '3 Bedrooms'), ('PENTHOUSE', 'Penthouse')], 
                default='STUDIO', 
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='unit',
            name='floor_level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='unit',
            name='size_sqm',
            field=models.DecimalField(
                decimal_places=2, 
                default=25.00, 
                help_text='Size in square meters', 
                max_digits=8
            ),
        ),
        migrations.AddField(
            model_name='unit',
            name='status',
            field=models.CharField(
                choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('MAINTENANCE', 'Under Maintenance'), ('RESERVED', 'Reserved')], 
                default='AVAILABLE', 
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='unit',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='amenities',
            field=models.TextField(
                blank=True, 
                help_text='List amenities separated by commas'
            ),
        ),
        migrations.AddField(
            model_name='unit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
        ),
        migrations.AddField(
            model_name='unit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
