# Generated by Django 6.0.2 on 2026-04-17 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_alter_unit_options_unit_monthly_rent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('SUCCESS', 'Success'), ('ERROR', 'Error'), ('LEASE', 'Lease Related'), ('PAYMENT', 'Payment Related'), ('MAINTENANCE', 'Maintenance Related'), ('UNIT', 'Unit Related')], default='INFO', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_tenant', models.ForeignKey(blank=True, help_text='Related tenant if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_notifications', to=settings.AUTH_USER_MODEL)),
                ('related_unit', models.ForeignKey(blank=True, help_text='Related unit if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentals.unit')),
                ('user', models.ForeignKey(blank=True, help_text='Specific user this notification is for (null means all admins)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
