# Generated by Django 6.0.2 on 2026-04-26 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantRiskClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk')], default='MEDIUM', max_length=10)),
                ('payment_score', models.IntegerField(default=50, help_text='Payment behavior score (0-100)')),
                ('late_payment_count', models.IntegerField(default=0, help_text='Number of late payments')),
                ('unpaid_bill_count', models.IntegerField(default=0, help_text='Current unpaid bills')),
                ('last_payment_date', models.DateTimeField(blank=True, help_text='Last successful payment date', null=True)),
                ('risk_factors', models.JSONField(default=dict, help_text='JSON object storing risk factors')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.OneToOneField(limit_choices_to={'role': 'TENANT'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tenant Risk Classification',
                'verbose_name_plural': 'Tenant Risk Classifications',
                'ordering': ['-risk_level', 'tenant__email'],
            },
        ),
    ]
