# Generated by Django 6.0.2 on 2026-04-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_tenantriskclassification'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantriskclassification',
            name='is_new_tenant',
            field=models.BooleanField(default=False, help_text='Tenant with less than 3 months of payment history'),
        ),
    ]
