# Generated by Django 6.0.2 on 2026-04-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_tenantriskclassification_is_new_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Room name/number', max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Room price per month', max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Room description and features')),
                ('image', models.ImageField(blank=True, help_text='Room image', null=True, upload_to='rooms/')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('MAINTENANCE', 'Under Maintenance')], default='AVAILABLE', help_text='Room status', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['name'],
            },
        ),
    ]
