# Generated by Django 6.0.2 on 2026-04-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='image',
            field=models.ImageField(blank=True, help_text='Unit image', null=True, upload_to='units/'),
        ),
    ]
