# Generated by Django 6.0.2 on 2026-04-29 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0008_unit_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='image',
        ),
        migrations.CreateModel(
            name='UnitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Unit image', upload_to='units/')),
                ('caption', models.CharField(blank=True, help_text='Image caption (optional)', max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='Set as primary/featured image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rentals.unit')),
            ],
            options={
                'verbose_name': 'Unit Image',
                'verbose_name_plural': 'Unit Images',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
