# Generated by Django 6.0.2 on 2026-04-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0009_remove_unit_image_unitimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantprofile',
            name='has_seen_unit_welcome',
            field=models.BooleanField(default=False, help_text='Track if tenant has seen the unit welcome popup'),
        ),
    ]
