# Generated by Django 6.0.2 on 2026-05-03 19:51

from django.db import migrations, models


def split_full_name(apps, schema_editor):
    """Split existing full_name into first_name and last_name"""
    TenantProfile = apps.get_model('rentals', 'TenantProfile')
    
    for profile in TenantProfile.objects.all():
        if profile.full_name:
            # Split the full name into parts
            name_parts = profile.full_name.strip().split()
            if len(name_parts) >= 2:
                # Take first part as first name, rest as last name
                profile.first_name = name_parts[0]
                profile.last_name = ' '.join(name_parts[1:])
            elif len(name_parts) == 1:
                # Only one name provided, use it as first name
                profile.first_name = name_parts[0]
                profile.last_name = ''
            else:
                # Empty name, use defaults
                profile.first_name = ''
                profile.last_name = ''
            
            profile.save()


def combine_full_name(apps, schema_editor):
    """Combine first_name and last_name back to full_name for rollback"""
    TenantProfile = apps.get_model('rentals', 'TenantProfile')
    
    for profile in TenantProfile.objects.all():
        if profile.first_name or profile.last_name:
            profile.full_name = f"{profile.first_name} {profile.last_name}".strip()
            profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0010_tenantprofile_has_seen_unit_welcome'),
    ]

    operations = [
        # Add new fields as nullable initially
        migrations.AddField(
            model_name='tenantprofile',
            name='first_name',
            field=models.CharField(max_length=60, default='', blank=True),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='last_name',
            field=models.CharField(max_length=60, default='', blank=True),
        ),
        
        # Migrate data
        migrations.RunPython(split_full_name, reverse_code=combine_full_name),
        
        # Make new fields non-nullable after data migration
        migrations.AlterField(
            model_name='tenantprofile',
            name='first_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='last_name',
            field=models.CharField(max_length=60),
        ),
        
        # Remove old full_name field
        migrations.RemoveField(
            model_name='tenantprofile',
            name='full_name',
        ),
    ]
