# Generated by Django 6.0.2 on 2026-05-03 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0012_add_tenant_attachments_and_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rentals.unit'),
        ),
    ]
