# Generated by Django 6.0.2 on 2026-05-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0013_change_unit_to_foreignkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='recipient_type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('TENANT', 'Tenant'), ('SPECIFIC_USER', 'Specific User')], default='SPECIFIC_USER', help_text='Type of recipient for role-based filtering', max_length=20),
        ),
    ]
