# Generated by Django 6.0.2 on 2026-05-05 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0015_add_notification_recipient_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='advance_months',
            field=models.PositiveSmallIntegerField(default=2, help_text='Number of months for advance payment'),
        ),
        migrations.AddField(
            model_name='lease',
            name='end_date',
            field=models.DateField(blank=True, help_text='Lease end date (optional)', null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Security deposit amount', max_digits=10),
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('RENT_DUE', 'Rent Due'), ('ADVANCE_PAYMENT', 'Advance Payment'), ('SECURITY_DEPOSIT', 'Security Deposit'), ('CONTRACT_START', 'Contract Start'), ('CONTRACT_END', 'Contract End')], max_length=20)),
                ('event_date', models.DateField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='rentals.lease')),
                ('tenant', models.ForeignKey(limit_choices_to={'role': 'TENANT'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['event_date'],
                'indexes': [models.Index(fields=['event_date', 'status'], name='rentals_cal_event_d_b5e335_idx'), models.Index(fields=['tenant', 'event_date'], name='rentals_cal_tenant__db9b19_idx'), models.Index(fields=['lease', 'event_type'], name='rentals_cal_lease_i_1dafd3_idx')],
            },
        ),
    ]
