# Generated by Django 6.0.2 on 2026-05-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0016_add_lease_payment_fields_and_calendar_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantprofile',
            name='password_change_required',
            field=models.BooleanField(default=False, help_text='Whether tenant should change password on first login'),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='send_credentials',
            field=models.BooleanField(default=True, help_text='Whether to send login credentials via email'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('INFO', 'Information'), ('SYSTEM', 'System'), ('BILLING', 'Billing'), ('MAINTENANCE', 'Maintenance'), ('UNIT', 'Unit Related')], default='INFO', max_length=20),
        ),
    ]
