# Generated by Django 6.0.2 on 2026-05-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0017_tenantprofile_password_change_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantriskclassification',
            name='rf_model_version',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tenantriskclassification',
            name='rf_risk_level',
            field=models.CharField(blank=True, choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tenantriskclassification',
            name='rf_risk_probability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantriskclassification',
            name='rf_top_factors',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
