# Generated by Django 6.0.2 on 2026-05-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0018_tenantriskclassification_rf_model_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='parking_type',
            field=models.CharField(choices=[('NONE', 'No Parking'), ('MOTORCYCLE', 'Motorcycle – ₱350/mo'), ('CAR', 'Car – ₱2,500/mo')], default='NONE', help_text='Parking slot type', max_length=12),
        ),
    ]
