# Generated by Django 6.0.2 on 2026-05-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0019_add_parking_to_lease_and_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='parking_type',
        ),
        migrations.AddField(
            model_name='lease',
            name='car_slots',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of car parking slots (₱2,500 each/mo)'),
        ),
        migrations.AddField(
            model_name='lease',
            name='motorcycle_slots',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of motorcycle parking slots (₱350 each/mo)'),
        ),
    ]
