# Generated by Django 6.0.2 on 2026-05-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0020_replace_parking_type_with_slots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='advance_months',
        ),
        migrations.AddField(
            model_name='lease',
            name='deposit_multiplier',
            field=models.PositiveSmallIntegerField(default=2, help_text='Contract deposit multiplier (security deposit = monthly_rent × this value)'),
        ),
    ]
