# Generated by Django 6.0.2 on 2026-05-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0021_rename_advance_months_to_deposit_multiplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('INFO', 'Information'), ('SYSTEM', 'System'), ('BILLING', 'Billing'), ('MAINTENANCE', 'Maintenance'), ('UNIT', 'Unit Related'), ('PAYMENT', 'Payment'), ('LEASE', 'Lease')], default='INFO', max_length=20),
        ),
    ]
