# Generated by Django 6.0.2 on 2026-05-25 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0022_alter_notification_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_user_id', models.IntegerField(help_text='Original User ID')),
                ('original_tenant_id', models.IntegerField(help_text='Original TenantProfile ID')),
                ('email', models.EmailField(help_text='Original email address', max_length=254)),
                ('tenant_data', models.JSONField(help_text='Complete snapshot of tenant data including profile, leases, payments, etc.')),
                ('archive_type', models.CharField(choices=[('DEACTIVATED', 'Deactivated - Records Preserved'), ('DELETED_SOFT', 'Soft Deleted - Archived Only'), ('DELETED_HARD', 'Hard Deleted - With Records')], default='DEACTIVATED', help_text='Type of deletion/archive action performed', max_length=20)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('deletion_reason', models.TextField(blank=True, help_text='Optional reason for deletion')),
                ('can_be_restored', models.BooleanField(default=True, help_text='Whether this tenant can be restored')),
                ('restored_at', models.DateTimeField(blank=True, help_text='When restored if applicable', null=True)),
                ('deleted_by', models.ForeignKey(help_text='Admin who performed the deletion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_tenants', to=settings.AUTH_USER_MODEL)),
                ('restored_by', models.ForeignKey(blank=True, help_text='Admin who restored the tenant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restored_tenants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archived Tenant',
                'verbose_name_plural': 'Archived Tenants',
                'ordering': ['-deleted_at'],
                'indexes': [models.Index(fields=['email'], name='rentals_arc_email_00c8cc_idx'), models.Index(fields=['deleted_at'], name='rentals_arc_deleted_7e5b92_idx'), models.Index(fields=['archive_type'], name='rentals_arc_archive_c096f3_idx')],
            },
        ),
    ]
