# Generated by Django 6.0.2 on 2026-05-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0023_archivedtenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantprofile',
            name='password_change_required',
            field=models.BooleanField(default=True, help_text='Whether tenant should change password on first login'),
        ),
    ]
