# Generated by Django 6.0.2 on 2026-05-25 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0024_password_change_required_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='activated_at',
            field=models.DateTimeField(blank=True, help_text='When lease was activated after payment', null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('ACTIVE', 'Active'), ('TERMINATED', 'Terminated'), ('EXPIRED', 'Expired')], default='PENDING_PAYMENT', help_text='Lease lifecycle status', max_length=20),
        ),
        migrations.AlterField(
            model_name='lease',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Whether lease is currently active (backward compatibility)'),
        ),
    ]
