# Generated by Django 6.0.2 on 2026-06-02 16:04

import rentals.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0028_notification_query_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, help_text='Room image', null=True, storage=rentals.storage.SupabaseStorage(), upload_to='rooms/'),
        ),
        migrations.AlterField(
            model_name='unitimage',
            name='image',
            field=models.ImageField(help_text='Unit image', storage=rentals.storage.SupabaseStorage(), upload_to='units/'),
        ),
    ]
