# Generated by Django 6.0.2 on 2026-06-15 15:23

import rentals.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0029_alter_room_image_alter_unitimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantattachment',
            name='file',
            field=models.FileField(help_text='Upload contract or valid ID', storage=rentals.storage.SupabaseStorage(bucket='user-files'), upload_to='tenant_attachments/'),
        ),
    ]
