# Generated by Django 6.0.2 on 2026-02-19 19:39

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=50)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('prev_reading', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('curr_reading', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('rate_per_cu_m', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted')], default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_bills', to='rentals.unit')),
            ],
            options={
                'ordering': ['-period_end', '-id'],
                'unique_together': {('unit', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='WaterCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='water.waterbill')),
            ],
        ),
    ]
