# Generated by Django 6.0.2 on 2026-05-06 13:05

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_monthlybill_bill_type'),
        ('rentals', '0017_tenantprofile_password_change_required_and_more'),
        ('water', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterbill',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_water_bills', to='rentals.unit'),
        ),
        migrations.CreateModel(
            name='WaterRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(help_text='Date when this rate becomes active')),
                ('rate_per_cu_m', models.DecimalField(decimal_places=2, help_text='Price per cubic meter (e.g., 45.00)', max_digits=12)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to disable this rate')),
                ('notes', models.TextField(blank=True, help_text="Optional notes (e.g., 'Supplier price increase June 2026')")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_water_rates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Water Rate',
                'verbose_name_plural': 'Water Rates',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='WaterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_month', models.DateField(help_text='Month being billed (enter 1st of month, e.g., 2026-06-01)')),
                ('previous_reading', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Previous meter reading (cubic meters)', max_digits=12)),
                ('current_reading', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current meter reading (cubic meters)', max_digits=12)),
                ('consumption', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Computed: Current - Previous (auto-filled)', max_digits=12)),
                ('rate_used', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Rate per m³ used for calculation (snapshot)', max_digits=12)),
                ('computed_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Computed: Consumption × Rate (auto-filled)', max_digits=12)),
                ('is_first_reading', models.BooleanField(default=False, help_text='Check if this is the initial move-in reading (no consumption charged)')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('lease', models.ForeignKey(help_text='Tenant lease (links to unit)', on_delete=django.db.models.deletion.CASCADE, related_name='water_readings', to='rentals.lease')),
                ('read_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_water_readings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Water Reading',
                'verbose_name_plural': 'Water Readings',
                'ordering': ['-reading_month', '-id'],
                'unique_together': {('lease', 'reading_month')},
            },
        ),
        migrations.CreateModel(
            name='WaterComputationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('computed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('monthly_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_computation_logs', to='billing.monthlybill')),
                ('water_reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computation_logs', to='water.waterreading')),
            ],
            options={
                'ordering': ['-computed_at'],
            },
        ),
    ]
