# Generated by Django 6.0.2 on 2026-06-03 07:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0002_alter_waterbill_unit_waterrate_waterreading_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='waterreading',
            name='base_water_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Computed: Consumption x rate', max_digits=12),
        ),
        migrations.AddField(
            model_name='waterreading',
            name='previous_unpaid_water_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Previous unpaid water balance included in this bill', max_digits=12),
        ),
        migrations.AddField(
            model_name='waterreading',
            name='shared_pump_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tenant share of shared pump charge', max_digits=12),
        ),
        migrations.AddField(
            model_name='waterreading',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='VAT amount snapshot', max_digits=12),
        ),
        migrations.AddField(
            model_name='waterreading',
            name='vat_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('12.00'), help_text='VAT percentage snapshot', max_digits=5),
        ),
        migrations.CreateModel(
            name='WaterBillingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_month', models.DateField(help_text='Month being billed (use first day of month)', unique=True)),
                ('shared_pump_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total shared pump charge to allocate by tenant usage', max_digits=12)),
                ('vat_percent', models.DecimalField(decimal_places=2, default=Decimal('12.00'), help_text='VAT percentage applied to water charge plus shared pump', max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_water_billing_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Water Billing Setting',
                'verbose_name_plural': 'Water Billing Settings',
                'ordering': ['-reading_month'],
            },
        ),
    ]
