# Generated by Django 6.0.2 on 2026-07-02 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(blank=True, default='Official Update', max_length=80)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField()),
                ('button_text', models.CharField(blank=True, max_length=40)),
                ('button_url', models.CharField(blank=True, default='#about', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_homepage_banners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Homepage banner',
                'verbose_name_plural': 'Homepage banners',
                'ordering': ['-is_active', '-updated_at', '-created_at'],
            },
        ),
    ]
