# Generated by Django 6.0.2 on 2026-07-02 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_homepagebanner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=160)),
                ('tagline', models.CharField(blank=True, max_length=220)),
                ('about_text', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=255)),
                ('inquiry_text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_business_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business profile',
                'verbose_name_plural': 'Business profiles',
                'ordering': ['-is_active', '-updated_at', '-created_at'],
            },
        ),
    ]
