# Generated by Django 6.0.2 on 2026-07-04 11:49

import django.db.models.deletion
import rentals.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_businessprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, storage=rentals.storage.SupabaseStorage(), upload_to='landing/features/')),
                ('icon_label', models.CharField(blank=True, max_length=40)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_landing_page_features', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Landing page feature',
                'verbose_name_plural': 'Landing page features',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LandingPageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(choices=[('hero', 'Hero'), ('about', 'About'), ('services', 'Services'), ('contact', 'Contact'), ('footer', 'Footer')], max_length=40, unique=True)),
                ('title', models.CharField(blank=True, max_length=180)),
                ('subtitle', models.CharField(blank=True, max_length=220)),
                ('body_text', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, storage=rentals.storage.SupabaseStorage(), upload_to='landing/sections/')),
                ('button_text', models.CharField(blank=True, max_length=60)),
                ('button_url', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_landing_page_sections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Landing page section',
                'verbose_name_plural': 'Landing page sections',
                'ordering': ['display_order', 'section_key'],
            },
        ),
    ]
