# Generated by Django 6.0.2 on 2026-07-04 12:40

import rentals.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_landingpagefeature_landingpagesection'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='about_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='about_image',
            field=models.ImageField(blank=True, null=True, storage=rentals.storage.SupabaseStorage(), upload_to='landing/content/about/'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='about_title',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='contact_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='contact_title',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='footer_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='hero_button_text',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='hero_button_url',
            field=models.CharField(blank=True, default='#about', max_length=255),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, storage=rentals.storage.SupabaseStorage(), upload_to='landing/content/hero/'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='hero_subtitle',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='hero_title',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='service_1_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='service_1_image',
            field=models.ImageField(blank=True, null=True, storage=rentals.storage.SupabaseStorage(), upload_to='landing/content/services/'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='service_1_title',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='service_2_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='service_2_image',
            field=models.ImageField(blank=True, null=True, storage=rentals.storage.SupabaseStorage(), upload_to='landing/content/services/'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='service_2_title',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='service_3_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='service_3_image',
            field=models.ImageField(blank=True, null=True, storage=rentals.storage.SupabaseStorage(), upload_to='landing/content/services/'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='service_3_title',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='services_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='services_title',
            field=models.CharField(blank=True, max_length=220),
        ),
    ]
