# Generated by Django 6.0.2 on 2026-07-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0005_businessprofile_about_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='hero_description',
            field=models.TextField(blank=True),
        ),
    ]
