# Generated by Django 6.0.2 on 2026-07-04 17:21

import announcements.models
import rentals.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0006_businessprofile_hero_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='about_image',
            field=models.ImageField(blank=True, null=True, storage=rentals.storage.SupabaseStorage(), upload_to=announcements.models.landing_about_upload_path),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, storage=rentals.storage.SupabaseStorage(), upload_to=announcements.models.landing_hero_upload_path),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='service_1_image',
            field=models.ImageField(blank=True, null=True, storage=rentals.storage.SupabaseStorage(), upload_to=announcements.models.landing_service_1_upload_path),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='service_2_image',
            field=models.ImageField(blank=True, null=True, storage=rentals.storage.SupabaseStorage(), upload_to=announcements.models.landing_service_2_upload_path),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='service_3_image',
            field=models.ImageField(blank=True, null=True, storage=rentals.storage.SupabaseStorage(), upload_to=announcements.models.landing_service_3_upload_path),
        ),
    ]
