# Generated by Django 6.0.2 on 2026-05-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_maintenancerequest_fixed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='nlp_priority',
            field=models.CharField(blank=True, default='', help_text='Priority predicted by NLP model from description text', max_length=10),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='nlp_priority_confidence',
            field=models.FloatField(blank=True, help_text='Confidence score (0.0-1.0) of the NLP priority prediction', null=True),
        ),
    ]
