# Generated by Django 6.0.5 on 2026-05-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_nlp_priority_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance_photos/'),
        ),
    ]
