# Generated by Django 6.0.2 on 2026-07-01 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def add_maintenance_staff_workflow_fields(apps, schema_editor):
    table_name = "maintenance_maintenancerequest"
    connection = schema_editor.connection

    with connection.cursor() as cursor:
        existing_columns = {
            column.name
            for column in connection.introspection.get_table_description(cursor, table_name)
        }

        if "assigned_staff_id" not in existing_columns:
            cursor.execute(
                """
                ALTER TABLE maintenance_maintenancerequest
                ADD COLUMN assigned_staff_id bigint NULL
                """
            )
        if "review_status" not in existing_columns:
            cursor.execute(
                """
                ALTER TABLE maintenance_maintenancerequest
                ADD COLUMN review_status varchar(20) NOT NULL DEFAULT 'PENDING'
                """
            )

        cursor.execute(
            """
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname = 'maintenance_req_assigned_staff_fk'
                ) THEN
                    ALTER TABLE maintenance_maintenancerequest
                    ADD CONSTRAINT maintenance_req_assigned_staff_fk
                    FOREIGN KEY (assigned_staff_id)
                    REFERENCES accounts_user(id)
                    ON DELETE SET NULL
                    DEFERRABLE INITIALLY DEFERRED;
                END IF;
            END $$;
            """
        )
        cursor.execute(
            """
            CREATE INDEX IF NOT EXISTS maintenance_req_assigned_staff_idx
            ON maintenance_maintenancerequest (assigned_staff_id)
            """
        )


def remove_maintenance_staff_workflow_fields(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            ALTER TABLE maintenance_maintenancerequest
            DROP CONSTRAINT IF EXISTS maintenance_req_assigned_staff_fk
            """
        )
        cursor.execute(
            """
            DROP INDEX IF EXISTS maintenance_req_assigned_staff_idx
            """
        )
        cursor.execute(
            """
            ALTER TABLE maintenance_maintenancerequest
            DROP COLUMN IF EXISTS assigned_staff_id
            """
        )
        cursor.execute(
            """
            ALTER TABLE maintenance_maintenancerequest
            DROP COLUMN IF EXISTS review_status
            """
        )


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_alter_maintenancerequest_photo_storage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_maintenance_staff_workflow_fields,
                    remove_maintenance_staff_workflow_fields,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='maintenancerequest',
                    name='assigned_staff',
                    field=models.ForeignKey(blank=True, help_text='Staff member assigned after admin acceptance.', limit_choices_to={'role': 'STAFF'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenance_requests', to=settings.AUTH_USER_MODEL),
                ),
                migrations.AddField(
                    model_name='maintenancerequest',
                    name='review_status',
                    field=models.CharField(choices=[('PENDING', 'Pending Admin Review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
                ),
            ],
        ),
    ]
