# Generated by Django 6.0.2 on 2026-07-04 20:57

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_alter_billlineitem_line_type'),
        ('maintenance', '0007_maintenancerequest_assigned_staff_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(blank=True, default='')),
                ('repair_notes', models.TextField(blank=True, default='')),
                ('labor_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('material_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('suggested_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('admin_approved_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('NO_CHARGE', 'No Charge'), ('APPROVED', 'Approved'), ('READY_FOR_BILLING', 'Ready for Billing'), ('ADDED_TO_BILL', 'Added to Bill')], default='PENDING_REVIEW', max_length=30)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_maintenance_charges', to=settings.AUTH_USER_MODEL)),
                ('bill_line_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_charges', to='billing.billlineitem')),
                ('maintenance_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='charge', to='maintenance.maintenancerequest')),
                ('suggested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_maintenance_charges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
